# ============================================================================
# Makefile.local.mk
#
# Append (or copy/paste) the contents of this file to the bottom of the
# Makefile generated by project-creator-cli, ABOVE the final
# `include $(CY_TOOLS_DIR)/make/start.mk` line.
#
# This wires our src/ tree, include/ path, and C++ flags into the MTB build.
# ============================================================================

# ----- C++ support -----
# arm-none-eabi-g++ is bundled with ModusToolbox. We just opt in.
CXXFLAGS+=-std=c++17
CXXFLAGS+=-fno-exceptions
CXXFLAGS+=-fno-rtti
CXXFLAGS+=-fno-threadsafe-statics
CXXFLAGS+=-Wall -Wextra -Wpedantic

# ----- Our source tree -----
# Pick up every .c/.cpp in our directories. As you add files, no Makefile edits
# needed — wildcard finds them.
SOURCES+=$(wildcard $(CY_APP_PATH)/main.cpp)
SOURCES+=$(wildcard $(CY_APP_PATH)/src/*.cpp)
SOURCES+=$(wildcard $(CY_APP_PATH)/src/drivers/*.cpp)
SOURCES+=$(wildcard $(CY_APP_PATH)/src/tasks/*.cpp)
SOURCES+=$(wildcard $(CY_APP_PATH)/src/middleware/*.cpp)
SOURCES+=$(wildcard $(CY_APP_PATH)/src/hal_glue/*.c)
SOURCES+=$(wildcard $(CY_APP_PATH)/src/ml/*.c)

# ----- Include search paths -----
INCLUDES+=$(CY_APP_PATH)/include
INCLUDES+=$(CY_APP_PATH)/src
INCLUDES+=$(CY_APP_PATH)/src/drivers
INCLUDES+=$(CY_APP_PATH)/src/tasks
INCLUDES+=$(CY_APP_PATH)/src/middleware
INCLUDES+=$(CY_APP_PATH)/src/ml

# Third-party (uncomment as vendored):
# INCLUDES+=$(CY_APP_PATH)/../third_party/BMI270-Sensor-API
# SOURCES+=$(wildcard $(CY_APP_PATH)/../third_party/BMI270-Sensor-API/*.c)

# ----- Components / features -----
# Add FREERTOS to enable the FreeRTOS middleware via ModusToolbox.
# Add NS for non-secure (the only option on this BSP) — usually already set.
# COMPONENTS+=FREERTOS

# ----- Log level (compile-time) -----
# 1=ERR 2=WARN 3=INFO 4=DEBUG 5=TRACE
DEFINES+=LOG_LEVEL=3
